---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: 14

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
  - name: ubuntu-18.04
    driver:
      image: ubuntu:18.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

suites:
  - name: default
    run_list: recipe[tgw_uwsgi::default]
