---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  product_version: 14

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list: recipe[tgw_uwsgi::default]
    attributes:
      uwsgi:
        emperor:
          enable: false
      authorization:
        sudo:
          groups: ['admin', 'wheel', 'sysadmin']
          users: ['vagrant']
          passwordless: 'true'
